"""Fixed serialization and relationships

Revision ID: 2519c1774ee8
Revises: cec386fadbbf
Create Date: 2025-06-12 15:40:49.612997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2519c1774ee8'
down_revision = 'cec386fadbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.create_unique_constraint('unique_student_subject_grade', ['student_id', 'subject_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_subject_grade', type_='unique')
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###
